[tool.poetry]
name = "signaloid"
version = "1.3.0"
description = ""
authors = [
    "Signaloid <info@signaloid.com>"
]

[tool.poetry.group.dev.dependencies]
wheel = "^0.42.0"
pex = "^2.1.159"
types-toml = "^0.10.8.7"
pytest = "^7.4.4"
mypy = "^1.8.0"
flake8 = "^7.0.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
numpy = "^1.26.4"
matplotlib = "^3.8.3"

[tool.mypy]
warn_unused_configs = true
strict = true

[[tool.mypy.overrides]]
module = [
	"signaloid.distributional_information_plotting.*",
	"signaloid.distributional.*",
]
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
warn_unused_ignores = false
check_untyped_defs = false
strict_equality = false

[[tool.mypy.overrides]]
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false

# , --check-untyped-defs, --disallow-untyped-decorators, --warn-redundant-casts, --warn-unused-ignores,
